server:
  port: 8082
spring:
  application:
    name: "msLoanApplications"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  webclient:
    users:
      base-url: "http://localhost:8082/api/v1/usuarios"
jwt:
  json-exp-roles: "/roles"
  secret: "miClaveSuperSecretaConAlMenos32Caracteres123!"
  expiration: 3600
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
  health:
    circuitbreakers:
      enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8082"
adapters:
  r2dbc:
    host: "localhost"
    port: 5435
    database: "postgres"
    schema: "credi_ya"
    username: "admin"
    password: "dbloanapplications"
  restconsumer:
    timeout: 5000
    url: "http://localhost:8080"
  sqs:
    decisions:
      region: us-east-2
      queueurl: https://sqs.us-east-2.amazonaws.com/484558640369/queue-loan
      #endpoint: # For localstack only
    capacity-calculation:
      region: us-east-2
      queueurl: https://sqs.us-east-2.amazonaws.com/484558640369/loan-capacity-check
      #endpoint:
    capacity-result:
      queueurl: "https://sqs.us-east-2.amazonaws.com/484558640369/loan-capacity-result-queue"
      region: "us-east-2"

logging:
  level:
    root: "INFO"
    org.springframework: "INFO"
    reactor.netty: "INFO"
    co.com.crediya: "DEBUG"
    org.springframework.security: "DEBUG"
    org.springframework.security.web.server: "DEBUG"
  pattern:
    console: "[%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} - %msg%n"
resilience4j:
  circuitbreaker:
    instances:
      clientService:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        waitDurationInOpenState: "10s"
