server:
  port: 8082
spring:
  application:
    name: "LoanApplication"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "https://idp.example.com/issuer"
          client-id: "myclientid"
jwt:
  json-exp-roles: "/roles"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8082"

adapters:
  r2dbc:
    host: localhost
    port: 5435
    database: postgres
    schema: credi_ya
    username: admin
    password: loanaplications

logging:
  level:
    root: INFO
    org.springframework: INFO
    reactor.netty: INFO
    co.com.crediya: DEBUG
  pattern:
    console: "[%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} - %msg%n"