server:
  port: 8082

spring:
  application:
    name: "LoanApplication"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"

jwt:
  json-exp-roles: "/roles"
  secret: "miClaveSuperSecretaConAlMenos32Caracteres123!"
  expiration: 3600

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
  health:
    circuitbreakers:
      enabled: true

cors:
  allowed-origins: "http://localhost:4200,http://localhost:8082"

adapters:
  r2dbc:
    host: ${DB_HOST:db_loanapplications}
    port: ${DB_PORT:5432}
    database: ${DB_NAME:postgres}
    schema: ${DB_SCHEMA:credi_ya}
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:db_loanapplications}
  restconsumer:
    timeout: 5000
    url: ${AUTHENTICATION_URL:http://ms_authentication:8080}
  sqs:
    capacity:
      region: us-east-2
      queueurl: https://sqs.us-east-2.amazonaws.com/123456789012/loan-capacity-check
      endpoint: http://localhost:4566
    decisions:
      region: us-east-2
      queueurl: ${SQS_DECISION_QUEUE_URL}
      endpoint: http://localhost:4566
    capacity-result:
      queueurl: "https://sqs.us-east-2.amazonaws.com/484558640369/loan-capacity-result-queue"
      region: "us-east-2"
    
logging:
  level:
    root: "INFO"
    org.springframework: "INFO"
    reactor.netty: "INFO"
    co.com.crediya: "DEBUG"
    org.springframework.security: DEBUG
    org.springframework.security.web.server: DEBUG
  pattern:
    console: "[%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} - %msg%n"
    
resilience4j:
  circuitbreaker:
    instances:
      clientService:   # 👈 este debe coincidir con el "name" en  @CircuitBreaker
        registerHealthIndicator: true
        failureRateThreshold: 50           # % de fallos permitido
        slowCallRateThreshold: 50          # % de llamadas lentas permitido
        slowCallDurationThreshold: 2s      # llamadas >2s se consideran lentas
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10              # ventana de 10 llamadas
        minimumNumberOfCalls: 5            # no activa hasta mínimo 5 llamadas
        waitDurationInOpenState: 10s 
